kafka:
  image: wurstmeister/kafka
  links:
    - zookeeper
  ports:
    - "9092:9092"
  environment:
    KAFKA_VERSION: "0.10.1.0"
    KAFKA_CREATE_TOPICS: "events:2:1,test:1:1"
    KAFKA_ADVERTISED_HOST_NAME: "localhost"
    KAFKA_ADVERTISED_PORT: "9092"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
